'use client'

import { createClient } from '@/lib/supabase/client'
import { useCallback, useEffect, useState } from 'react'

interface UseRealtimeChatProps {
  roomName: string
  username: string
}

export interface ChatMessage {
  id: string
  content: string
  user: {
    name: string
  }
  createdAt: string
  parentId?: string
  replyCount?: number
}

const EVENT_MESSAGE_TYPE = 'message'

export function useRealtimeChat({ roomName, username }: UseRealtimeChatProps) {
  const supabase = createClient()
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [channel, setChannel] = useState<ReturnType<typeof supabase.channel> | null>(null)
  const [isConnected, setIsConnected] = useState(false)

  useEffect(() => {
    const newChannel = supabase.channel(roomName)

    newChannel
      .on('broadcast', { event: EVENT_MESSAGE_TYPE }, (payload) => {
        setMessages((current) => [...current, payload.payload as ChatMessage])
      })
      .subscribe(async (status) => {
        if (status === 'SUBSCRIBED') {
          setIsConnected(true)
        }
      })

    setChannel(newChannel)

    return () => {
      supabase.removeChannel(newChannel)
    }
  }, [roomName, username, supabase])

  const sendMessage = useCallback(
    async (content: string, parentId?: string | null) => {
      if (!channel || !isConnected) return

      // Save message to database first to get the generated ID
      const supabase = createClient()
      console.log('Saving message with parent_id:', parentId)
      
      const { data, error } = await supabase.from('messages').insert({
        content,
        user_name: username,
        parent_id: parentId || null
      }).select()
      
      if (error) {
        console.error('Error saving message:', error)
        return
      } 
      
      console.log('Message saved successfully:', data)
      
      // Use the ID generated by Supabase
      const savedMessage = data[0]
      const message: ChatMessage = {
        id: savedMessage.id,
        content,
        user: {
          name: username,
        },
        createdAt: savedMessage.created_at,
        parentId: parentId || undefined,
      }

      // Update local state
      // setMessages((current) => [...current, message])

      // Broadcast message to other clients
      await channel.send({
        type: 'broadcast',
        event: EVENT_MESSAGE_TYPE,
        payload: message,
      })
    },
    [channel, isConnected, username]
  )

  return { messages, sendMessage, isConnected }
}